### ISSUE TITLE
secret or public key must be provided

### ISSUE THREAD

**Issue by Amialc** [auth0-samples/auth0-express-api-samples#1]
(AUTH-3808)
Using `02-Authenticate-RS256` sample from `p1` branch, I've received error:
![image](https://cloud.githubusercontent.com/assets/1114365/23512668/11f3dbf4-ff6a-11e6-8d22-929d1e851b8d.png)

**Comment by Amialc** [comment]
Error was in misconfiguration client, my signing alrogithm was `HS256`

**Comment by truggn** [comment]
đéo biết

**Comment by truggn** [comment]
tao cũng bị lỗi giống thằng lồn trên,
