### ISSUE TITLE
how to get the additional data to access private path correctly? any steps?

### ISSUE THREAD

**Issue by adamchenwei** [auth0-samples/auth0-express-api-samples#18]
https://github.com/auth0-samples/auth0-express-api-samples/tree/master/01-Authorization-RS256
Specifically for this example. since it said `A protected endpoint which returns a message on success. Requires a valid JWT access token with a scope of read:messages.`
how to obtain / setup both so to pass the private route?

**Comment by mathiasconradt** [comment]
Similar question came up in the Auth0 forum here: https://community.auth0.com/t/how-to-secure-an-api-with-auth0/19636 The answer there provides relevant links with instructions in the docs.

**Comment by mathiasconradt** [comment]
This should be a relevant doc with instructions to start with: https://auth0.com/docs/microsites/protect-api/protect-api

**Comment by adamchenwei** [comment]
Resolved here, in case anyone needed help with same thing
https://community.auth0.com/t/nobody-is-answering-my-question-in-github-issue-thought-i-ask-here-again/27806
