### ISSUE TITLE
Use audience instead of client_id in .env

### ISSUE THREAD

**Issue by cascadian** [auth0-samples/auth0-express-api-samples#2]
The .env file names the variable as client_id, when what's actually needed is the audience of the API. When downloading this sample from the [Auth0 website ](https://auth0.com/docs/quickstart/backend/nodejs/03-authenticate-rs256), it inserted the client_id of my "Default App" client when I expected it to use the audience of my API.

**Comment by chenkie** [comment]
The setup here is actually meant to be used with the legacy way of interacting with Auth0 which has the `id_token` sent to the API. In this setup, the `client_id` is required as the audience. The new samples and docs will be live soon and I'm just about to push a new branch to this repo which shows it :)
