### ISSUE TITLE
Refused to load the image 'http://localhost:3010/favicon.ico'

### ISSUE THREAD

**Issue by sarezas** [auth0-samples/auth0-express-api-samples#24]
### Refused to load the image 'http://localhost:3010/favicon.ico' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback.

Angular CLI: 8.3.5
Node: 12.10.0
OS: linux x64

Error is thrown right after 
npm install and npm start

**Comment by joshcanhelp** [comment]
@sarezas - Where is this error appearing? And you mention Angular as well, I'm not sure how that is related. 

I just ran this sample as-is without an issue at all. If you can provide more details here, I'm happy to take a look.
