### ISSUE TITLE
Invalid compact JWS

### ISSUE THREAD

**Issue by andrewhamili** [auth0-samples/auth0-express-api-samples#42]
![image](https://user-images.githubusercontent.com/20767537/184459388-ae37a093-b2b1-4b36-ac6d-db044c12e12e.png)

What seems to be the problem here? I cannot get it to work.

**Comment by adamjmcgrath** [comment]
Hi @andrewhamili - have a look at https://github.com/auth0/node-oauth2-jwt-bearer/issues/69#issuecomment-1191185036

**Comment by ewanharris** [comment]
Closing based on previous comment, please ping to reopen if you'd like to continue discussion.
